name: Red

on:
    schedule:
        # Runs every Sunday at 23:00 UTC from Sep 7 to Oct 26 (inclusive).
        - cron: "0 23 * 9-10 0"
            
    workflow_dispatch:

permissions:
    contents: read

concurrency:
    group: monday-window
    cancel-in-progress: true

env:
  TZ: Europe/Copenhagen
  layout: "Red"



jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Download leaderboard exports
        run: python3 download_leaderboard_exports.py --season seasons/summer_league.yml

      - name: Generate leaderboard
        run: python3 process_leaderboard.py --season_yaml seasons/summer_league.yml --sheet "Pool ${{ env.layout }} - Round 1" --output "Leaderboard_${{ env.layout }}.csv"

      - name: Upload leaderboard artifact
        uses: actions/upload-artifact@v4
        with:
          name: leaderboard
          path: ${{ github.workspace }}/Leaderboard_${{ env.layout }}.csv
          if-no-files-found: error