name: White

on:
    schedule:
        # Runs every Sunday at 23:00 UTC from Sep 7 to Oct 26 (inclusive).
        - cron: "0 23 * 9-10 0"
            
    workflow_dispatch:

permissions:
    contents: read

concurrency:
    group: monday-window
    cancel-in-progress: true

env:
  TZ: Europe/Copenhagen
  leaderboard_file: leaderboard_white.csv
  sheet_name: "Pool White - Round 1"



jobs:
    calculate_leaderboard:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Upload leaderboard artifact
              uses: actions/upload-artifact@v4
              with:
                name: leaderboard
                path: ${{ github.workspace }}/${{ vars.leaderboard_file }}
                if-no-files-found: error

            - name: Do work
              run: |
                python3 -m pip install pandas openpyxl requests
                python3 download_leaderboard_exports.py
                python3 process_leaderboard.py --sheet "${{ vars.sheet_name }}" --output ${{ vars.leaderboard_file }}